blog/urls.py
from django.urls import path
from .views import *

from django.conf.urls.static import static
from django.conf import settings

appname = "blog"

urlpatterns = [
    path('', posts_list, name='posts_list_url'),
    # path('post/create/', PostCreate.as_view(), name='post_create_url'),
    path('<str:slug>/', post_detail, name='post_detail_url')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taplink/urls.py
from django.urls import path
from .views import links_list

from django.conf.urls.static import static
from django.conf import settings

appname = "taplink"

urlpatterns = [
    path('', links_list, name='links_list_url'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thes_ml/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('golem/', admin.site.urls),
    path('s/', include('shortURI.urls')),
    path('go/', include('taplink.urls')),
    path('', include('blog.urls')),
    path('', include('pagedown.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

handler404 = 'blog.views.error_404'

taplink/models.py
from django.db import models
from solo.models import SingletonModel

class Link(models.Model):
    l_created = models.DateTimeField(auto_now_add=True)
    l_name = models.CharField(max_length=80, blank=True)
    l_url = models.URLField()
    l_followed = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["-l_created"]
        verbose_name = "Link"

    def __str__(self):
        return self.l_url

    # def save(self, *args, **kwargs):
    #     if not self.short_url:
    #         self.short_url = create_shortened_url(self)
    #
    #     super().save(*args, **kwargs)

class Social(models.Model):
    SOCIAL = (
        ('tg', 'telegram'),
        ('fb', 'facebook-f'),
        ('twi', 'twitter'),
        ('ins', 'instagram'),
        ('li', 'linkedin'),
        ('yt', 'youtube'),
        ('git', 'github'),
        ('be', 'behance'),
    )
    s_name = models.CharField(choices=SOCIAL, max_length=4)
    s_url = models.URLField()
    s_followed = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = "Social"

    def __str__(self):
        return f'{self.s_name} ({self.s_url})'



class TapLinkConfiguration(SingletonModel):
    site_name = models.CharField(max_length=255, default='@thes.ml')
    logo = models.ImageField(upload_to='taplink/')
    note = models.CharField(max_length=255, default='All Links')

    class Meta:
        verbose_name = "TapLink Configuration"

    def __str__(self):
        return "TapLink Configuration"

taplink/views.py
from django.shortcuts import render

from .models import Link, Social

def links_list(request):
    links = Link.objects.all()
    socials = Social.objects.all()

    context = {
        'links': links,
        'socials': socials
    }

    return render(request, 'taplink/links_list.html', context=context)

templates/taplink/links_list.html
{% load static %}
{% load solo_tags %}
{% get_solo 'taplink.TapLinkConfiguration' as tlink %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>All Links | thes.ml</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
</head>

<body class="bg-secondary">
<div class="container">
    <div class="col-10 mx-auto my-3">
        <img src="{{ tlink.logo.url }}" class="img-fluid rounded-circle mx-auto d-block" alt="logo" width="300" height="300">
        <div class="text-center text-white my-2">
            <h1>{{ tlink.site_name }}</h1>
            <h4>{{ tlink.note }}</h4>
        </div>
    </div>

    <ul class="list-inline text-center mx-auto">
        {% for social in socials %}
            <li class="list-inline-item">
                <a class="btn link-light" style="" href="{{ social.s_url }}" type="button">
                    <i class="fab fa-{{ social.get_s_name_display }} fa-2x"></i>
                </a>
            </li>
        {% endfor %}
    </ul>

    <div class="d-grid gap-2 col-10 mx-auto">
        {% for link in links %}
            <a href="{{ link.l_url }}" class="btn btn-light mb-3" type="button">{{ link.l_name }}</a>
        {% endfor %}
    </div>
</div>
</body>
</html>